project:
  # The acquia_subname value is the machine name of your subscription on Acquia
  # Cloud. E.g., if your dev env URL on Acquia Cloud is
  # http://psprojectdev.prod.acquia-sites.com/ then your acquia_subname is
  # "psproject". This value is used to correctly configure settings in
  # settings.php includes. This will also determine the the directory name
  # of the new repository.
  acquia_subname: 'capitalcamp'
  # Used for enforcing correct git commit msg syntax.
  prefix: 'DGC'
  human_name: 'Drupal GovCon'
  # This is the default makefile that will be used to build dependencies.
  # It should live in the project root.
  make_file: 'make.yml'
  profile:
    name: 'cod'
    # Please ensure contrib profiles are also in your make file.
    contrib: true
  # This is used to build front end artifacts. E.g., SASS compilation.
  themes:
    - govcon_2016

# Configuration settings for new git repository.
git:
  default_branch: develop
  remotes:
    # Defining git remotes allows builds deployed via CI.
    # Only add git repositories that you would like to deploy to!
    - capitalcamp@svn-6971.prod.hosting.acquia.com:capitalcamp.git

deploy:
  branch: "develop-build"
  commitMsg: "Automated commit by Travis CI."
