<?php
/**
 * @file
 * Install, update and uninstall functions for the dgc_deploy module.
 */

/**
 * Improve usability of login form with super_login module
 */
function dgc_deploy_update_7000() {
  module_enable(array('super_login'));
}

/**
 * Improve usability of registration and login actions with logintoboggan module
 */
function dgc_deploy_update_7001() {
  module_enable(array('logintoboggan'));
}
